//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCachedApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCachedApplication.Properties.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Users (
        ///    Id INTEGER PRIMARY KEY,
        ///    FirstName TEXT NOT NULL,
        ///    LastName TEXT NOT NULL,
        ///    FullName TEXT NOT NULL,
        ///    UserName TEXT NOT NULL,
        ///    Email TEXT NOT NULL,
        ///    Avatar TEXT NOT NULL,
        ///    CartId TEXT NOT NULL,
        ///    SSN TEXT NOT NULL,
        ///    Gender TEXT NOT NULL
        ///).
        /// </summary>
        internal static string UsersCreate {
            get {
                return ResourceManager.GetString("UsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id,
        ///    FirstName,
        ///    LastName,
        ///    FullName,
        ///    UserName,
        ///    Email,
        ///    Avatar,
        ///    CartId,
        ///    SSN,
        ///    Gender
        ///FROM
        ///    Users
        ///ORDER BY
        ///    Id DESC.
        /// </summary>
        internal static string UsersGetAll {
            get {
                return ResourceManager.GetString("UsersGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users 
        ///(
        ///    FirstName,
        ///    LastName,
        ///    FullName,
        ///    UserName,
        ///    Email,
        ///    Avatar,
        ///    CartId,
        ///    SSN,
        ///    Gender
        ///)
        ///VALUES
        ///(
        ///    @FirstName,
        ///    @LastName,
        ///    @FullName,
        ///    @UserName,
        ///    @Email,
        ///    @Avatar,
        ///    @CartId,
        ///    @SSN,
        ///    @Gender
        ///).
        /// </summary>
        internal static string UsersInsert {
            get {
                return ResourceManager.GetString("UsersInsert", resourceCulture);
            }
        }
    }
}
